### ISSUE TITLE
[ENHANCEMENT] Bearer token should be copyable and not truncated

### ISSUE THREAD

**Issue by kennethvl** [payfazz/fazz_tools_ui#6]
- Bearer token kepotong
- Sebaiknya bisa dicopy juga Bearer tokennya

**Comment by azharprabudi** [comment]
All information except response / request body already implemented with copy component. So all the content can be copy inside it. [Here the implementation](https://github.com/payfazz/fazz_tools_ui/commit/4d41bd0624e8157c5a7033ea3132356974e2bb33)
