### ISSUE TITLE
[BUG] Error displayed when request body is empty on GET request

### ISSUE THREAD

**Issue by kennethvl** [payfazz/fazz_tools_ui#7]
Muncul error:
```
{
  "message": "src property must be a valid json object"
}
```

untuk request GET yang tidak punya body atau query

**Comment by azharprabudi** [comment]
Add handling for nullable request / response body at [here](https://github.com/payfazz/fazz_tools_ui/commit/5fd7ef85ec4901dbe5ec2f65cc7bbb0f9ca68204)
